apiVersion: v1
kind: LimitRange
metadata:
  name: men-cpu-limit-practica
  namespace: practica 
spec:
  limits:
  - max:
      cpu: "1"
      memory: "2Gi"
    min:
      cpu: "0.3"
      memory: "500Mi"
    default:
      cpu: "0.8"
      memory: "1.5Gi"
    defaultRequest:
      cpu: "0.5"
      memory: "1Gi"
    type: Container
