# Generated by Django 3.0 on 2020-02-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Rol',
        ),
    ]
