# Generated by Django 3.0 on 2020-03-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200225_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='schedule.Student'),
        ),
    ]
